
; [mysql]
mysql_hostname     = 127.0.0.1
mysql_port         = 3306
mysql_user         = root
mysql_pass         = shx19930509321
mysql_databasename = payflow

;日志配置
;[logconf]
log_maxAge       = 365 ;//日志最大保存时间（天）
log_rotationTime = 24  ;//日志切割时间间隔（小时）
log_Path         = "./log"
log_FileName     = "settlementMonitoring.log"

;黑名单mysql配置 "root:"+pwd+"@tcp(122.51.24.189:3307)/blacklist?charset=utf8"
;"root:Microvideo_1@tcp(122.51.24.189:3307)/blacklist?charset=utf8&parseTime=true&loc=Local"
;[hmysql]
hmysql_hostname     = 122.51.24.189
hmysql_port         = 3307
hmysql_user         = root
hmysql_pass         = Microvideo_1
hmysql_databasename = blacklis

;[redis]
redis_addr         = "192.168.200.170:6379"
redis_pass         = Microvideo_1
redis_databasename = "3"

;[ip_address]
ip_address          =127.0.0.1:8088

